<?php

/**
 * PluginmyFaqItemTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginmyFaqItemTable extends myBaseTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginmyFaqItemTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginmyFaqItem');
    }

    /**
     * Возвращает сгруппированные записи
     *
     * @return array
     */
    public function getGrouped()
    {
        $items = $this->withI18n(null, 'a')
            ->orderBy('a.group_name')
            ->addOrderBy('atrans.question')
            ->execute()->getData();

        $groups = array();
        foreach ($items as $item) {
            $groups[$item->getGroupName()][] = $item;
        }

        ksort($groups);
        return $groups;
    }
}