# FAQ
myFaqItem:
  tableName: my_faq_items
  actAs:
    I18n:
      fields:               [question, answer]
  columns:
    group_name:             { type: string(64), notnull: true }
    #I18n
    question:               { type: string, notnull: true }
    answer:                 { type: string, notnull: true }
